from collections import Counter
from pathlib import Path

from src.models.report import Report


class HTMLReportGenerator:
    """
    Generates an HTML report from a Report object.
    """

    def generate(
        self,
        report: Report,
        output_file: str = "reports/truthlens_report.html",
    ) -> Path:

        severity = Counter()

        for issue in report.issues:
            severity[issue.severity.name] += 1

        html = f"""
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>TruthLens Report</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    background: #f4f6f8;
    margin: 40px;
}}

.container {{
    max-width: 1000px;
    margin: auto;
}}

.card {{
    background: white;
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 20px;
    box-shadow: 0 2px 8px rgba(0,0,0,.1);
}}

h1 {{
    margin-top: 0;
}}

.score {{
    font-size: 48px;
    font-weight: bold;
    color: #2563eb;
}}

.ready {{
    color: green;
    font-weight: bold;
}}

.not-ready {{
    color: red;
    font-weight: bold;
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

th,
td {{
    padding: 10px;
    border-bottom: 1px solid #ddd;
    text-align: left;
}}

.issue {{
    margin-top: 15px;
    border-left: 5px solid #2563eb;
    padding-left: 15px;
}}

.footer {{
    text-align: center;
    color: gray;
    margin-top: 40px;
}}

</style>

</head>

<body>

<div class="container">

<div class="card">

<h1>TruthLens Analysis Report</h1>

<div class="score">
{report.trust_score:.2f}/100
</div>

<p>
<b>Production Ready:</b>

<span class="{"ready" if report.production_ready else "not-ready"}">
{"YES" if report.production_ready else "NO"}
</span>

</p>

<p>

<b>Total Issues:</b>

{len(report.issues)}

</p>

</div>

<div class="card">

<h2>Issue Summary</h2>

<table>

<tr>

<th>Severity</th>

<th>Count</th>

</tr>

<tr><td>CRITICAL</td><td>{severity.get("CRITICAL",0)}</td></tr>

<tr><td>HIGH</td><td>{severity.get("HIGH",0)}</td></tr>

<tr><td>MEDIUM</td><td>{severity.get("MEDIUM",0)}</td></tr>

<tr><td>LOW</td><td>{severity.get("LOW",0)}</td></tr>

</table>

</div>

<div class="card">

<h2>Issue Details</h2>

{"".join(
    f'''
<div class="issue">

<h3>[{issue.severity.name}] {issue.title}</h3>

<p><b>Line:</b> {issue.line if issue.line else "-"}</p>

<p>{issue.message}</p>

<p>

<b>Recommendation:</b>

{issue.recommendation}

</p>

</div>
'''
for issue in report.issues
) if report.issues else "<p>No issues detected.</p>"}

</div>

<div class="footer">

Generated by TruthLens

</div>

</div>

</body>

</html>
"""

        output_path = Path(output_file)

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        output_path.write_text(
            html,
            encoding="utf-8",
        )

        return output_path
